apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: verhalenbank
  name: verhalenbank-webroot
  namespace: verhalenbank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
